version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - /mnt/nginx/sites-available:/etc/nginx/sites-available
      - /mnt/nginx/sites-enabled:/etc/nginx/sites-enabled
      - /mnt/nginx/www:/var/www
      - /mnt/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"


